BS-2549: Typed PDP request
build-security/opa-java-spring-client pull request #7
Opened 2021-01-17 16:12 UTC by amirbenun

2021-01-19 07:30 UTC, shahar-davidson requested changes
See comments.
In addition:

1. Please update the README file accordingly
2. Please try to add some inline documentation especially on classes/fields which customers are expected to use as part of the API 
3. Please note my comment regarding the fact that these changes break the API of 0.30 and prior versions - we should not do that
4. How can we allow more flexibility for users who simply want to pass their own input structure and not be locked to the PdpRequest input structure?
5. Missing UT for: PdpdRequestProvider, PdpInterceptor, PDPEnforcer

2021-01-19 07:30 UTC, shahar-davidson commented on src/main/java/build/security/pdp/client/PDPClient.java
> +    public JsonNode getJsonResponse(PdpRequest request) throws Throwable {
Changing the signature of an public API call is a breaking change .
(1) when we do breaking changes we should start a new major version (e.g. 1.0.0)
(2) I don't think we should do breaking changes (TEG have already started using the client and possibly also Guidewire) - I think we should use method overloading so that `getJsonResponse` could **also** receive a `PdpRequest` - this way you could extend the API without breaking it

2021-01-19 07:30 UTC, shahar-davidson commented on src/main/java/build/security/pdp/client/PDPClient.java
> +    public Map<String, Object> getMappedResponse(PdpRequest request) throws Throwable {
Same here - this is changes breaks the API

2021-01-19 07:30 UTC, shahar-davidson commented on src/main/java/build/security/pdp/request/PdpRequestProvider.java
> +        PdpRequestInput input = new PdpRequestInput(incomingHttp, resources, "", "");
why are we passing empty values for source and destination?
If we cannot provide these values on this C'tor then why have them at all?

2021-01-19 07:30 UTC, shahar-davidson commented on src/main/java/build/security/pdp/client/PDPEnforcer.java
> +    public Boolean RunAuthorization(HttpServletRequest request, String[] requirements) {
I would rename it to AuthorizeRequest ...

2021-01-19 07:30 UTC, shahar-davidson commented on src/main/java/build/security/pdp/client/PdpInterceptor.java
> +        String[] requirements = new String[0];
who/what populates the `requirements`? 
I didn't see where in the code it gets populate - am I missing something?

2021-01-19 07:30 UTC, shahar-davidson commented on src/main/java/build/security/pdp/client/PDPClient.java
> +public class PdpClient {
The file name should have the same name capitalization (check other classes and files here as well)

2021-01-19 09:39 UTC, amirbenun commented on src/main/java/build/security/pdp/client/PdpInterceptor.java
> +        String[] requirements = new String[0];
I added the missing parts

2021-01-19 09:48 UTC, amirbenun commented on example/src/main/java/security/build/WebSecurityConfig.java
> +//         http.authorizeRequests().antMatchers("/websecurity").authenticated().accessDecisionManager(accessDecisionManager());
Remove this file?

2021-01-19 11:23 UTC, amirbenun commented on src/main/java/build/security/pdp/client/PDPClient.java
> +public class PdpClient {
I sticked to your convention capitalised `PDP` in file name and class name

2021-01-19 14:14 UTC, shahar-davidson requested changes
See latest comments.
Please run the unit-tests with a coverage report and make sure the coverage looks good. (cover the business logic and critical areas)

2021-01-19 14:14 UTC, shahar-davidson commented on example/src/main/java/security/build/WebSecurityConfig.java
> +//         http.authorizeRequests().antMatchers("/websecurity").authenticated().accessDecisionManager(accessDecisionManager());
If everything works without this file then it can be removed

2021-01-19 14:14 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PDPClient.java
>       * @return a JsonNode response for the given request.
The `@param` description is not accurate

2021-01-19 14:14 UTC, shahar-davidson commented on src/main/java/security/build/pdp/request/PDPRequestProvider.java
> +        String ipAddress = request.getHeader("X-FORWARDED-FOR");
Good that you look at the x-forwarded-for header but please not that it may return a list of IPs: https://en.wikipedia.org/wiki/X-Forwarded-For

2021-01-19 14:14 UTC, shahar-davidson commented on src/main/java/security/build/pdp/request/PDPRequestProvider.java
> +    private String GetSourceIp(HttpServletRequest request) {
please add a UT for this method

2021-01-19 14:46 UTC, amirbenun commented on src/main/java/security/build/pdp/request/PDPRequestProvider.java
> +    private String GetSourceIp(HttpServletRequest request) {
There is one already `Provide_ForwardedRequest_ContainsOriginalSource` in `PDPRequestProviderTest.java`

2021-01-19 14:56 UTC, amirbenun commented on README.md
> +PDP is registered as a spring interceptor
Returned that example to the readme

2021-01-19 15:04 UTC, amirbenun commented
![image](https://user-images.githubusercontent.com/34831306/105052220-4e3b0c00-5a78-11eb-808b-c99439206f61.png)

2021-01-19 15:08 UTC, amirbenun commented on src/main/java/security/build/pdp/request/PDPRequestProvider.java
> +        String ipAddress = request.getHeader("X-FORWARDED-FOR");
Actually I think the current behaviour is not so bad, the mw is in charge of reflecting the request to the PDP which it does.

2021-01-20 09:51 UTC, shahar-davidson requested changes

2021-01-20 09:51 UTC, shahar-davidson commented on src/test/java/security/build/pdp/request/PDPRequestProviderTest.java
> +    void Provide_ForwardedRequest_ContainsOriginalSource() {
This test should be improved (and possibly the logic there), because as you can see [here](https://en.wikipedia.org/wiki/X-Forwarded-For) the header can contain a several IPs such as:
`X-Forwarded-For: 203.0.113.195, 70.41.3.18, 150.172.238.178`

2021-01-20 09:51 UTC, shahar-davidson commented on src/main/java/security/build/pdp/request/PDPRequestProvider.java
> +        String ipAddress = request.getHeader("X-FORWARDED-FOR");
what I meant is that the x-forwarded-for can return a list of IPs such as:
`X-Forwarded-For: 203.0.113.195, 70.41.3.18, 150.172.238.178` 
and in such a case the function will return the string with all the IPs and not just the source IP.
The logic of this function should take the 1st IP in the list as the source IP.

2021-01-20 11:28 UTC, shahar-davidson approved these changes

2021-01-20 14:38 UTC, merged